### ISSUE TITLE
setAudioVolume as a string

### ISSUE THREAD

**Issue by s3Pol** [aparraga/braviarc#21]
Hi,

I just find out that the volume should be set as a string not as int.
I also tested with a string and the set works fine...

```
"If you look at the setAudioVolume method definition in the audio.getMethodTypes() response:

["setAudioVolume", [{
	"target": "string",
	"volume": "string"
}], ["int"], "1.0"]

The volume needs to be given as a string and not as an integer."
```

https://github.com/waynehaffenden/bravia/issues/3

**Comment by rchl** [comment]
I have [fixed that](https://github.com/gerard33/sony_bravia_psk/pull/3) in a fork of this repo. Hopefully it will eventually replace original code.
