### ISSUE TITLE
Issue pairing with Brava TV (XBR850C & XBR830C)

### ISSUE THREAD

**Issue by frostronic** [aparraga/braviarc#3]
Greetings,

I'm not sure if this is the correct venue for this, but I'm having issues pairing my TVs with the braviarc HomeAssistant implementation.

I tried using the HA configurator as directed, but after I enter 0000, the TV flashes a code momentarily and then says the pair was cancelled. HA immediately adds the TV without ever prompting for the code and then the TV shows up as a media player card, however it doesn't do anything or update status (obviously the pair didn't complete successfully.) I've deleted the bravia.conf in the hass root directory and tried to repair multiple times with the same result.

Also, every time I reboot HA, the TVs display the pairing request dialog from HA, but HA never gives me the option to enter a code.

I have two Bravia XBRs, 850C & 830C, same result with both.

Any advice?

**Comment by antonioparraga** [comment]
Let me figure out what's wrong...

**Comment by rafaelmagu** [comment]
I've hit the same issue and found that if I wrote the PIN into `bravia.conf` manually and restarted HA, it worked. I then found out the power commands don't seem to work on the 850C (only Android-based one I have). But that's something for another issue, which I logged here: https://github.com/home-assistant/home-assistant/issues/2599

**Comment by antonioparraga** [comment]
I thinks this issue is fixed by #4
